[phases.setup]
nixPkgs = ['...']

[phases.build]
cmds = [
  "cd backend",
  "chmod +x ./gradlew",
  "./gradlew bootJar"
]

[start]
cmd = "cd backend && java -jar build/libs/backend-0.0.1-SNAPSHOT.jar"